# Generated by Django 5.2.4 on 2025-10-24 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0002_profile_address_profile_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='quantity_issued',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='devicerequest',
            name='imei_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='DeviceIMEI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei_number', models.CharField(max_length=50, unique=True)),
                ('is_available', models.BooleanField(default=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imeis', to='invent.device')),
            ],
            options={
                'ordering': ['-added_on'],
            },
        ),
        migrations.AddField(
            model_name='devicerequest',
            name='imei_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_requests', to='invent.deviceimei'),
        ),
        migrations.AddField(
            model_name='issuancerecord',
            name='imei',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issuance_records', to='invent.deviceimei'),
        ),
    ]
