# Generated by Django 5.2.3 on 2025-10-26 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0003_device_quantity_issued_devicerequest_imei_no_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Waiting Approval', 'Waiting Approval'), ('Issued', 'Issued'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('Partially Returned', 'Partially Returned'), ('Fully Returned', 'Fully Returned')], default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='SelectedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_on', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invent.device')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_devices', to='invent.devicerequest')),
                ('selected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
