# Generated by Django 5.2.3 on 2025-10-05 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0003_country_profile_branch_alter_devicerequest_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='purchase_orders/'),
        ),
    ]
