# Generated by Django 5.2.3 on 2025-10-26 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0003_device_quantity_issued_devicerequest_imei_no_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'permissions': [('can_issue_item', 'Can issue device to client'), ('can_return_item', 'Can record device returns')]},
        ),
    ]
