# Generated by Django 5.2.3 on 2025-10-26 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0004_alter_device_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_for_requests', to='invent.device')),
                ('device_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='invent.devicerequest')),
                ('selected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_selections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
