# Generated by Django 5.2.3 on 2025-10-10 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0005_purchaseorder_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='mac_address',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='imei_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='oem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='invent.oem', to_field='oem_id'),
        ),
        migrations.AlterField(
            model_name='device',
            name='product_id',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
