# Generated by Django 5.2.3 on 2025-10-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0006_device_mac_address_alter_device_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.CharField(blank=True, help_text='e.g. Laptop or Router', max_length=100),
        ),
    ]
