# Generated by Django 5.2.3 on 2025-10-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0007_alter_device_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='oem',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
