# Generated by Django 5.2.3 on 2025-10-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0007_selecteddevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Waiting Approval', 'Waiting Admin Approval'), ('Issued', 'Issued'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('Partially Returned', 'Partially Returned'), ('Fully Returned', 'Fully Returned')], default='Pending', max_length=20),
        ),
    ]
