# Generated by Django 5.2.3 on 2025-12-08 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0008_alter_devicerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicerequest',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
    ]
