# Generated by Django 5.2.3 on 2025-10-16 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0008_alter_device_oem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='oem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='invent.oem', to_field='oem_id'),
        ),
    ]
