# Generated by Django 5.2.3 on 2025-12-15 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0009_devicerequest_payment_proof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='device',
            name='selling_price',
        ),
    ]
