# Generated by Django 5.2.3 on 2025-12-16 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0010_remove_device_currency_remove_device_selling_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='imei_no',
        ),
        migrations.RemoveField(
            model_name='device',
            name='mac_address',
        ),
        migrations.RemoveField(
            model_name='device',
            name='quantity_issued',
        ),
        migrations.RemoveField(
            model_name='device',
            name='serial_no',
        ),
        migrations.RemoveField(
            model_name='device',
            name='total_quantity',
        ),
        migrations.RemoveField(
            model_name='devicerequest',
            name='imei_no',
        ),
        migrations.AddField(
            model_name='deviceimei',
            name='mac_address',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='deviceimei',
            name='serial_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='DeviceRequestSelectedIMEI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('date_selected', models.DateTimeField(auto_now_add=True)),
                ('device_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_imeis', to='invent.devicerequest')),
                ('imei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invent.deviceimei')),
            ],
        ),
    ]
