# Generated by Django 5.2.3 on 2025-12-20 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0011_remove_device_imei_no_remove_device_mac_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuancerecord',
            name='imei_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invent.deviceimei'),
        ),
    ]
