# Generated by Django 5.2.3 on 2026-01-06 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0012_issuancerecord_imei_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='selecteddevice',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selecteddevice',
            name='imei',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='invent.deviceimei'),
        ),
        migrations.AddField(
            model_name='selecteddevice',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
