# Generated by Django 5.2.3 on 2026-01-06 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0013_selecteddevice_approved_selecteddevice_imei_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceReports',
            fields=[
            ],
            options={
                'verbose_name': 'Device Request Report',
                'verbose_name_plural': 'Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('invent.devicerequest',),
        ),
    ]
