# Generated by Django 5.2.3 on 2025-09-18 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0013_box_client_office_supplier_device_issuancerecord_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='mac_address',
        ),
    ]
