# Generated by Django 5.2.3 on 2026-01-06 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0014_devicereports'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceReports',
        ),
        migrations.CreateModel(
            name='DeviceReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_requests', models.IntegerField(default=0)),
                ('pending_requests', models.IntegerField(default=0)),
                ('approved_requests', models.IntegerField(default=0)),
                ('issued_requests', models.IntegerField(default=0)),
                ('rejected_requests', models.IntegerField(default=0)),
                ('fully_returned_requests', models.IntegerField(default=0)),
                ('partially_returned_requests', models.IntegerField(default=0)),
                ('total_returned_quantity', models.IntegerField(default=0)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='invent.branch')),
            ],
            options={
                'verbose_name': 'Device Request Report',
                'verbose_name_plural': 'Device Request Reports',
            },
        ),
    ]
