# Generated by Django 5.2.3 on 2025-09-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0014_remove_device_mac_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocktransaction',
            options={},
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_id',
            field=models.CharField(default='SUP-000', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone_email',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
