# Generated by Django 5.2.3 on 2025-09-20 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0015_alter_stocktransaction_options_supplier_supplier_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='product_id',
            field=models.CharField(default='PROD-001', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='invent.supplier', to_field='supplier_id'),
        ),
    ]
