# Generated by Django 5.2.4 on 2025-09-25 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0016_device_product_id_device_supplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='stocktransaction',
            options={'ordering': ['-transaction_date'], 'permissions': [('can_issue_item', 'Can issue inventory items'), ('can_adjust_stock', 'Can adjust inventory stock'), ('can_receive_stock', 'Can receive new stock into inventory')]},
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='invent.box'),
        ),
        migrations.AlterField(
            model_name='box',
            name='number',
            field=models.PositiveIntegerField(help_text='Sequential number of the box', unique=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='condition',
            field=models.CharField(choices=[('Serviceable', 'Serviceable'), ('Not Serviceable', 'Not Serviceable'), ('Not working', 'Not working'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], default='Serviceable', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='issued_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='item_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to='invent.itemrequest'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='invent.category'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='invent.category'),
        ),
        migrations.CreateModel(
            name='Requestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requestor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invent.device')),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invent.requestor')),
            ],
        ),
    ]
