# Generated by Django 5.2.3 on 2025-09-26 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0017_devicerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicerequest',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_requests', to='invent.client'),
        ),
    ]
