# Generated by Django 5.2.4 on 2025-09-25 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0017_category_alter_stocktransaction_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='category',
        ),
    ]
