# Generated by Django 5.2.3 on 2025-09-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0018_devicerequest_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='total_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
