# Generated by Django 5.2.3 on 2025-09-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0019_device_name_device_total_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='product_id',
            field=models.CharField(max_length=30),
        ),
    ]
