# Generated by Django 5.2.3 on 2025-09-28 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0020_alter_device_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='box',
        ),
        migrations.DeleteModel(
            name='Box',
        ),
    ]
