# Generated by Django 5.2.3 on 2025-09-30 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0021_remove_device_box_delete_box'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemrequest',
            name='item',
        ),
        migrations.RemoveField(
            model_name='stocktransaction',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemrequest',
            name='requestor',
        ),
        migrations.RemoveField(
            model_name='stocktransaction',
            name='item_request',
        ),
        migrations.RemoveField(
            model_name='stocktransaction',
            name='recorded_by',
        ),
        migrations.DeleteModel(
            name='InventoryItem',
        ),
        migrations.DeleteModel(
            name='ItemRequest',
        ),
        migrations.DeleteModel(
            name='StockTransaction',
        ),
    ]
