# Generated by Django 5.2.3 on 2025-10-01 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0022_remove_itemrequest_item_remove_stocktransaction_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuancerecord',
            name='device_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issuances', to='invent.devicerequest'),
        ),
        migrations.AlterField(
            model_name='issuancerecord',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invent.client'),
        ),
    ]
