# Generated by Django 5.2.3 on 2025-10-03 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invent', '0023_issuancerecord_device_request_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('country', models.CharField(choices=[('Tanzania', 'Tanzania'), ('Kenya', 'Kenya')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OEM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oem_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone_email', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Office',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='device',
            name='supplier',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='selling_price_ksh',
            new_name='selling_price',
        ),
        migrations.RemoveField(
            model_name='device',
            name='selling_price_tsh',
        ),
        migrations.RemoveField(
            model_name='device',
            name='selling_price_usd',
        ),
        migrations.AddField(
            model_name='device',
            name='country',
            field=models.CharField(blank=True, choices=[('Tanzania', 'Tanzania'), ('Kenya', 'Kenya')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('TZS', 'Tanzanian Shilling'), ('KES', 'Kenyan Shilling')], default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='device',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='devicerequest',
            name='country',
            field=models.CharField(blank=True, choices=[('Tanzania', 'Tanzania'), ('Kenya', 'Kenya')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invent.branch'),
        ),
        migrations.AddField(
            model_name='devicerequest',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invent.branch'),
        ),
        migrations.AddField(
            model_name='device',
            name='oem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='invent.oem', to_field='oem_id'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='oem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='invent.oem'),
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
